workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:|\[WIP\]|WIP:)/
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # trigger on tag
    - if: '$CI_COMMIT_TAG =~ /^5.3.*/ || $CI_COMMIT_TAG =~ /^m5.3.*/'
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - test
  - build
  - image

variables:
  CLICOLOR_FORCE: '1'
  GIT_SUBMODULE_STRATEGY: recursive
  # NPM_PROXY: '1'

include:
  - .gitlab-ci/template.yaml

# TODO: docker image build
# --> pull latest mon, deploy custom dist on top

# TODO: makefile install

client:lint:
  stage: test
  extends: .lint
  variables:
    WHERE: Moki/client

server:lint:
  stage: test
  extends: .lint
  variables:
    WHERE: Moki/server

client:test:
  stage: test
  extends: .test
  variables:
    WHERE: Moki/client

server:test:
  stage: test
  extends: .test
  variables:
    WHERE: Moki/server

client:build:
  stage: build
  image: docker.frafos.net/debian/mon-builder:5.3
  interruptible: true
  script:
    - npm install --prefix Moki/client --omit-dev
    - npm run build --prefix Moki/client
  needs:
    - client:test
    - client:lint
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /^(.*,)?ci-skip-tests(,.*)*$/
      when: never
    - changes:
        - Moki/client/**

docker:dist:
  stage: build
  needs: []
  image: docker.frafos.net/debian/mon-builder:5.3
  script:
    - make install DESTDIR=`pwd`/dist
  artifacts:
    expire_in: 1h
    paths:
      - dist

docker:overlay:
  stage: image
  image: docker.frafos.net/docker:20.10-ci
  interruptible: true
  needs:
    - docker:dist
  services:
  - name: docker.frafos.net/docker:20.10-dind
    alias: docker
  script:
    - make pull-base pull-build
    - make overlay
    - docker push docker.frafos.net/debian/mon-overlay:5.3
