workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:|\[WIP\]|WIP:)/
      when: never
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # trigger on tag
    - if: '$CI_COMMIT_TAG =~ /^5.3.*/ || $CI_COMMIT_TAG =~ /^m5.3.*/'
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - test
  - build

# TODO: docker image build ? pull latest mon, deploy custom dist on top
# TODO: call to make
# TODO: color

.lint:
  image: docker.frafos.net/debian/mon-builder:5.3
  interruptible: true
  allow_failure: true
  variables:
    WHERE: ''
  script:
    - npm install --prefix $WHERE
    - npm run lint --prefix $WHERE
    # TODO: artifacts to gitlab

client:lint:
  stage: test
  extends: .lint
  variables:
    WHERE: Moki/client
    # TODO: rules

server:lint:
  stage: test
  extends: .lint
  variables:
    WHERE: Moki/server
    # TODO: rules

.test:
  image: docker.frafos.net/debian/mon-builder:5.3
  interruptible: true
  variables:
    WHERE: ''
  script:
    - npm install --prefix $WHERE
    - npm run test --prefix $WHERE
    # TODO: convert for gitlab CI report
    # TODO: coverage

client:test:
  stage: test
  extends: .test
  variables:
    WHERE: Moki/client
    # TODO: rules

server:test:
  stage: test
  extends: .test
  variables:
    WHERE: Moki/server
    # TODO: rules

.build:
  image: docker.frafos.net/debian/mon-builder:5.3
  interruptible: true
  variables:
    WHERE: ''
  script:
    - npm install --prefix $WHERE --omit-dev
    - npm run build --prefix $WHERE
    # TODO: artifacts

client:build:
  stage: build
  extends: .build
  variables:
    WHERE: Moki/client
    # TODO: rules

server:build:
  stage: build
  extends: .build
  variables:
    WHERE: Moki/server
    # TODO: rules
