version: "3.4"

services:

  front:
    build:
      context: client
      target: prod
      dockerfile: Dockerfile.prod
    container_name: moki-front
    restart: always
    environment:
      API_PORT: 5000
    ports:
      - 3000:3000

  api:
    build:
      context: server
      target: prod
    container_name: moki-api
    restart: always
    environment:
      API_PORT: 5000
      ADDR: 0.0.0.0
    ports:
      - 5000:5000

  # nginx is used for ssl termination
  nginx:
    restart: always
    build:
      context: nginx
      target: prod
    container_name: moki-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front
      - api

# volumes:
#   api_data:
