version: "3.4"

services:

  api:
    build:
      context: server
      target: dev
    container_name: moki-api-dev
    environment:
      API_PORT: 5000
    ports:
      - 5000:5000
    network_mode: "host"
    volumes:
      - "./server:/app"

  front:
    build:
      context: client
      target: dev
    container_name: moki-front-dev
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - "./client:/app"

      # nginx is used for ssl termination
  nginx:
    build:
      context: nginx
      target: dev
    restart: always
    # image: docker.frafos.net/license-nginx:latest
    container_name: moki-nginx-dev
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    depends_on:
      - api
      - front

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
  #   container_name: moki-es-dev
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
