version: "3.4"

volumes:
  node_modules:

services:

  front:
    build:
      context: client
      target: dev
    container_name: moki-front-dev
    environment:
      API_PORT: 5000
    ports:
      - 3000:3000
    # network_mode: "host"
    volumes:
       - "./client:/app"
       - node_modules:/app/node_modules:rw

  api:
    build:
      context: server
      target: dev
    container_name: moki-api-dev
    environment:
      API_PORT: 5000
      ADDR: 0.0.0.0
    ports:
      - 5000:5000
    # network_mode: "host"
    volumes:
      - "./server:/app"

  # nginx is used for ssl termination
  nginx:
    build:
      context: nginx
      target: dev
    restart: always
    container_name: moki-nginx-dev
    ports:
      - 80:80
      - 443:443
    # network_mode: "host"
    depends_on:
      - api
      - front

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
  #   container_name: moki-es-dev
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
