version: "3.4"

services:

  server:
    build:
      context: server
      target: dev
    container_name: moki-express-dev
    environment:
      API_PORT: 5000
    ports:
      - 5000:5000
    network_mode: "host"
    volumes:
      - "./server:/app"

  client:
    build:
      context: client
      target: dev
    container_name: moki-react-dev
    ports:
      - 3000:3000
    network_mode: "host"
    volumes:
      - "./client:/app"

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
  #   container_name: moki-es-dev
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
