name: pipeline

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  
jobs:

  client-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"

    - name: Install
      run: npm install --prefix Moki/client

    - name: Lint
      run: npm run lint --prefix Moki/client

  client-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"

    - name: Install
      run: npm install --prefix Moki/client

    - name: Test
      run: npm run test --prefix Moki/client

  client-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"

    - name: Install
      run: npm install --prefix Moki/client --omit-dev

    - name: Build
      run: npm run build --prefix Moki/client
